#!/usr/bin/python3

def raise_exception():
    try:
        result = "string" + 5
        print("Exception raised")
